sudo: true
language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
env:
  - MYSQL_VERSION=mysql-5.6
  - MYSQL_VERSION=mysql-5.7
services:
  - mysql
before_install:
  - gem update bundler
  - sudo apt-get -qq update
  - bash .travis/install_mysql.sh
before_script:
  - mysql --version
script:
  - bundle install
  - bundle exec rake
